apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-restart-deployment
  labels:
    app: hotel-restart
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotel-restart
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hotel-restart
    spec:
      containers:
      - name: hotel-restart-app
        image: hotel-restart-app:v1  # Jenkins will dynamically replace this tag with the ECR URL
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
